DROP TABLE IF EXISTS CLIENT;
  
CREATE TABLE CLIENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  age NUMBER(5)	NOT NULL,
  dni VARCHAR(9) NOT NULL,
  email VARCHAR(50) NOT NULL
);